# Generated by Django 3.1.1 on 2020-09-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200913_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yourblog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('blogy', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='cars')),
            ],
        ),
    ]
