# Generated by Django 3.1.1 on 2020-09-28 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_yourblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourblog',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
