# Generated by Django 3.1.1 on 2020-09-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_yourblog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourblog',
            name='blogy',
            field=models.CharField(max_length=1000),
        ),
    ]
